Social_Media_project/App_Login/urls.py
from django.urls import path
from App_Login import views



app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
]

Social_Media_project/App_Posts/urls.py
from App_Posts import views
from django.urls import path

app_name="App_Posts"

urlpatterns = [
    path("", views.home, name="home"),
    path("liked/<pk>", views.liked, name="liked"),
    path("unliked/<pk>", views.unliked, name="unliked"),
]

Social_Media_project/Social_Media_project/urls.py
from django.contrib import admin
from django.urls import path, include
from App_Posts import views

# display media/ image
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.home, name='home'),
]


# media / image
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Social_Media_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
    
    <!-- popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js" integrity="sha512-TPh2Oxlg1zp+kz3nFA0C5vVC6leG/6mm1z9+mA81MI5eaUVqasPLO8Cuk4gMF4gUfP5etR73rgU/8PNMsSesoQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- fontawesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">



    <title>{% block title_block %} Social {% endblock %}</title>


    {% block css_block %}

    {% endblock %}


</head>
<body>

    <div class="container" style="padding: 20px 0 20px 0">
        {% block body_block %} {% endblock %}
    </div>

</body>
</html>

Social_Media_project/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
    
    <!-- popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js" integrity="sha512-TPh2Oxlg1zp+kz3nFA0C5vVC6leG/6mm1z9+mA81MI5eaUVqasPLO8Cuk4gMF4gUfP5etR73rgU/8PNMsSesoQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- fontawesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">



    <title>{% block title_block %} Social {% endblock %}</title>


    {% block css_block %}

    {% endblock %}


</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'App_Posts:home' %}">Home</a>
            </li>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <li class="nav-item">

                {% comment %} search_bar from w3schools bootstrap{% endcomment %}
                <form class="form-inline" method="GET">
                    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>

            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
            </li>

            <li class="nav-item">
                {% comment %} 
                    # check j profile pic set kora ache kina
                    # 'user_profile' is the related name
                    # 'profile_pic' , a field_name in models.py
                {% endcomment %}
                {% if user.user_profile.profile_pic %}
                    <a class="nav-link" href="{% url 'App_Login:profile' %}">
                        <img src="/media/{{user.user_profile.profile_pic}}" width="40px" height="40px" class="rounded-circle">
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'App_Login:profile' %}">
                        <img src="/media/default_profile_pic.png"  width="40px" height="40px" class="rounded-circle">
                    </a>
                {% endif %}
            </li>
        </ul>
    </nav>

    <div class="container" style="padding: 30px 0 20px 0">
        {% block body_block %} {% endblock %}
    </div>

</body>
</html>